#!/usr/bin/env python
import re
import sys

#bash_name = re.sub(r'\.\d+\.py', '', sys.argv[0])
class RecordType:
	class Comment:
		name = 'comment';
	class ElemHide:
		name = 'elemHide';
	class AddressMatch:
		name = 'addressMatch';

	commentRx = re.compile('^!');
	elemHideRx = re.compile('^(.*)(#@?#)(.+)$');

	@staticmethod
	def match(line):
		if RecordType.commentRx.match(line):
			return RecordType.Comment;
		if RecordType.elemHideRx.match(line):
			return RecordType.ElemHide;
		return RecordType.AddressMatch;


class Record:
	def __init__ (self, line):
		self.line = line;
		self.type = RecordType.match(line);

def parseLine(line):
	record = Record(line);
	return [record];

def parse(filename):
    with open(filename) as f:
    	content = f.readlines();
    return [ record for line in content for record in parseLine(line) ];
 
def main():
    if len(sys.argv) > 1:
        for record in parse(sys.argv[1]):
    		print record.line[:-1] + '  (' + record.type.name + ')';
    else:
        print "Usage: parser <parameter>"
 
if __name__ == "__main__":
    main()