
# blocking with no options
{+block{adblock2 request block} \
 +server-header-tagger{block-any-response-ab2p} \
}
test.site


# unblocking with no options
{-block \
 +server-header-tagger{unblock-any-response-ab2p} \
}
test2.site



# blocking with SCRIPT option
{
 +client-header-tagger{block-script-request-ab2p} \
 +server-header-tagger{block-script-response-ab2p} \
}
test.site

# unblocking with SCRIPT option
{
 +client-header-tagger{unblock-script-request-ab2p} \
 +server-header-tagger{unblock-script-response-ab2p} \
}
test.site






# request blocking
{+block{adblock2 response block} \
}
TAG:^ADBLOCK_C_BLOCK


# response blocking
{+block{adblock2 response block} \
}
TAG:^ADBLOCK_S_BLOCK



# request unblocking
{-block \
}
TAG:^ADBLOCK_C_UNBLOCK

# response unblocking
{-block \
}
TAG:^ADBLOCK_S_UNBLOCK








