name: Docker Image CI

on:
  push:
    branches: [ genfiles ]
  pull_request:
    branches: [ genfiles ]
  create:
    branches: [ genfiles ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag privoxy-adb:$(date +%s)
